<?php
    $gerente_mantenimiento=[
        'users.create',
        'users.show',
        'users.edit',
        'users.store',
        'users.update',
        'users.destroy',
        'users.index',

        'profiles.create',
        'profiles.show',
        'profiles.edit',
        'profiles.store',
        'profiles.update',
        'profiles.destroy',

        'sistemas.create',
        'sistemas.show',
        'sistemas.edit',
        'sistemas.store',
        'sistemas.update',
        'sistemas.destroy',
        'sistemas.index',
        'sistemas.formImportExcel',

        'subsistemas.show',
        'subsistemas.create',
        'subsistemas.edit',
        'subsistemas.store',
        'subsistemas.update',
        'subsistemas.destroy',
        'subsistemas.index',
        'subsistemas.formImportExcel',

        'equipos.show',
        'equipos.create',
        'equipos.edit',
        'equipos.store',
        'equipos.update',
        'equipos.destroy',
        'equipos.index',
        'equipos.formImportExcel',

        'equipocaracteristica.show',
        'equipocaracteristica.edit',
        'equipocaracteristica.update',
        'equipocaracteristica.clone',
        'equipocaracteristica.index',
        'equipocaracteristica.imagen',
        'equipocaracteristica.imagenStore',
        'equipocaracteristica.caracteristicas',

        'tipos.show',
        'tipos.create',
        'tipos.edit',
        'tipos.store',
        'tipos.update',
        'tipos.destroy',
        'tipos.index',
        'tipos.formImportExcel',

        'parametros.show',
        'parametros.create',
        'parametros.edit',
        'parametros.store',
        'parametros.update',
        'parametros.destroy',
        'parametros.index',
        'parametros.formImportExcel',

        'feriados.create',
        'feriados.show',
        'feriados.edit',
        'feriados.store',
        'feriados.update',
        'feriados.destroy',
        'feriados.index',

        'userzonas.create',
        'userzonas.show',
        'userzonas.edit',
        'userzonas.store',
        'userzonas.update',
        'userzonas.destroy',
        'userzonas.index',
        'userzonas.formImportExcel',

        'equipozonas.create',
        'equipozonas.show',
        'equipozonas.edit',
        'equipozonas.store',
        'equipozonas.update',
        'equipozonas.destroy',
        'equipozonas.index',
        'equipozonas.formImportExcel',
       ];



