<?php
$gerente_planificacion=[
    'plans.create',
    'plans.show',
    'plans.edit',
    'plans.store',
    'plans.update',
    'plans.destroy',
    'plans.index',
    'plans.add',
    'plans.addStore',
    'plans.creaTarea',
    'plans.ajustes',
    'plans.mdf',

    'protocolos.create',
    'protocolos.show',
    'protocolos.edit',
    'protocolos.store',
    'protocolos.update',
    'protocolos.destroy',
    'protocolos.index',
    'protocolos.formImportExcel',

    'tipoprotocolos.create',
    'tipoprotocolos.show',
    'tipoprotocolos.edit',
    'tipoprotocolos.store',
    'tipoprotocolos.update',
    'tipoprotocolos.clone',
    'tipoprotocolos.index',
    'tipoprotocolos.imagen',

    'tipocaracteristicas.create',
    'tipocaracteristicas.show',
    'tipocaracteristicas.edit',
    'tipocaracteristicas.store',
    'tipocaracteristicas.update',
    'tipocaracteristicas.clone',
    'tipocaracteristicas.index',
    'tipocaracteristicas.imagen',

    'teamplans.index',
    'teamplans.store',
    'teamplans.taskteam',

    'feriados.create',
    'feriados.show',
    'feriados.edit',
    'feriados.store',
    'feriados.update',
    'feriados.destroy',
    'feriados.index',

];

