<?php
$jefe_supervisores = [
    //'sistemas.create',
    'sistemas.show',
    //'sistemas.edit',
    //'sistemas.store',
    //'sistemas.update',
    //'sistemas.destroy',
    'sistemas.index',
    //'sistemas.formImportExcel',

    'subsistemas.show',
    // 'subsistemas.create',
    // 'subsistemas.edit',
    // 'subsistemas.store',
    // 'subsistemas.update',
    // 'subsistemas.destroy',
    'subsistemas.index',
    //'subsistemas.formImportExcel',

    'equipos.show',
    // 'equipos.create',
    // 'equipos.edit',
    // 'equipos.store',
    // 'equipos.update',
    // 'equipos.destroy',
    'equipos.index',
    //'equipos.formImportExcel',

    'equipocaracteristica.show',
    // 'equipocaracteristica.edit',
    // 'equipocaracteristica.update',
    // 'equipocaracteristica.clone',
    // 'equipocaracteristica.index',
    'equipocaracteristica.imagen',
    // 'equipocaracteristica.imagenStore',
    // 'equipocaracteristica.caracteristicas',

    'tipos.show',
    //'tipos.create',
    // 'tipos.edit',
    // 'tipos.store',
    // 'tipos.update',
    // 'tipos.destroy',
    'tipos.index',
    //'tipos.formImportExcel',

    'parametros.show',
    // 'parametros.create',
    // 'parametros.edit',
    // 'parametros.store',
    // 'parametros.update',
    // 'parametros.destroy',
    'parametros.index',
    //'parametros.formImportExcel',

    //'insumos.create',
    'insumos.show',
    // 'insumos.edit',
    // 'insumos.store',
    // 'insumos.update',
    // 'insumos.destroy',
    'insumos.index',
    //'insumos.formImportExcel',


    //'herramientas.create',
    'herramientas.show',
    // 'herramientas.edit',
    // 'herramientas.store',
    // 'herramientas.update',
    // 'herramientas.destroy',
    'herramientas.index',
    //'herramientas.formImportExcel',

    //'servicios.create',
    'servicios.show',
    // 'servicios.edit',
    // 'servicios.store',
    // 'servicios.update',
    // 'servicios.destroy',
    'servicios.index',
    //'servicios.formImportExcel',

    //'repuestos.create',
    'repuestos.show',
    // 'repuestos.edit',
    // 'repuestos.store',
    // 'repuestos.update',
    // 'repuestos.destroy',
    'repuestos.index',
    //'repuestos.formImportExcel',


    //'protocolos.create',
    'protocolos.show',
    // 'protocolos.edit',
    // 'protocolos.store',
    // 'protocolos.update',
    // 'protocolos.destroy',
    'protocolos.index',
    //'protocolos.formImportExcel',

    'teams.index',
    //'teams.create',
    'teams.show',
    // 'teams.edit',
    // 'teams.store',
    // 'teams.update',
    //'teams.destroy',

    'teamfallas.create',
    'teamfallas.show',
    'teamfallas.edit',
    'teamfallas.store',
    'teamfallas.update',
    'teamfallas.destroy',
    'teamfallas.index',
    'teamfallas.formImportExcel',


    //'userzonas.create',
    'userzonas.show',
    // 'userzonas.edit',
    // 'userzonas.store',
    // 'userzonas.update',
    // 'userzonas.destroy',
    'userzonas.index',
    //'userzonas.formImportExcel',

    //'equipozonas.create',
    'equipozonas.show',
    // 'equipozonas.edit',
    // 'equipozonas.store',
    // 'equipozonas.update',
    // 'equipozonas.destroy',
    'equipozonas.index',
    //'equipozonas.formImportExcel',

    'userfallas.create',
    'userfallas.show',
    'userfallas.edit',
    'userfallas.store',
    'userfallas.update',
    'userfallas.destroy',
    'userfallas.index',
    //'userfallas.formImportExcel',

    //'fallas.create',
    'fallas.show',
    // 'fallas.edit',
    // 'fallas.store',
    // 'fallas.update',
    // 'fallas.destroy',
    'fallas.index',
    //'fallas.formImportExcel',
];
